platform :ios, '11'
use_frameworks!

target 'ComponentKitExample' do
  pod 'ThemeKit.swift', :path => '../'
  pod 'UIExtensions.swift', :path => '../../gui-kit/'
end

target 'ComponentKitTests' do
  pod 'ThemeKit.swift', :path => '../'
end
