platform :ios, '13'
use_frameworks!

target 'ComponentKitExample' do
  pod 'ThemeKit.swift', path: '../'
  pod 'LanguageKit.swift', path: '../'
  pod 'StorageKit.swift', path: '../'
  pod 'PinKit.swift', path: '../'
  pod 'CurrencyKit.swift', path: '../'
  pod 'ModuleKit.swift', path: '../'
  pod 'ComponentKit.swift', path: '../'

  pod 'UIExtensions.swift', git: 'https://github.com/horizontalsystems/gui-kit/'
  # pod 'UIExtensions.swift', path: '../../gui-kit/'
  pod 'HUD.swift', git: 'https://github.com/horizontalsystems/gui-kit/'
  # pod 'HUD.swift', path: '../../gui-kit/'
  pod 'SectionsTableView.swift', git: 'https://github.com/horizontalsystems/gui-kit/'
end

def testPods
  pod 'Quick'
  pod 'Nimble'
  pod 'Cuckoo'
  pod 'RxBlocking', '~> 5.0'
end

target 'PinKitTests' do
  pod 'PinKit.swift', :path => '../'
  testPods
end
